const {chromium}=require('playwright'),assert=require('assert/strict'),path=require('path'),fs=require('fs');
const url=process.env.GAME_URL||'http://127.0.0.1:8769/',key='dreamy-nights-chapter-one-v1',out=path.resolve(__dirname,'../test-results');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN}),errors=[];try{
 const setup=await b.newPage();await setup.addInitScript(()=>localStorage.setItem('dreamy-nights-opening-v1','seen'));await setup.goto(url);await setup.waitForFunction(()=>window.DreamGame?.inspect().mode==='title');await setup.click('#startButton');await setup.click('#confirmHero');await setup.click('#dialogueSkip');const seed=await setup.evaluate(()=>{const s=DreamGame.inspect().state;s.flags.introSeen=true;s.flags.firstMemory=true;s.flags.metLumen=true;s.map=0;s.hp=2;s.x=100;s.y=651;s.rpg.fragments=40;DREAM_GEAR.add(s.rpg,'tideBaton',2);s.rpg.gear.filter(g=>g.itemId==='tideBaton')[1].level=2;s.rpg.inventory.cookie=1;s.rpg.inventory.tea=1;s.rpg.inventory.softScarf=1;return s;});await setup.close();
 const open=async(width,height,fixture)=>{const mobile=width<1000,p=await b.newPage({viewport:{width,height},isMobile:mobile,hasTouch:mobile});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({key,fixture})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(fixture));localStorage.setItem('dreamy-nights-opening-v1','seen');localStorage.setItem('dreamy-nights-settings-v1',JSON.stringify({sound:false,voice:false}));window.requestAnimationFrame=()=>1;},{key,fixture});await p.goto(url);await p.waitForFunction(()=>window.DreamGame?.inspect().mode==='title');await p.click('#continueButton');await p.click('#inventoryButton');return p;};
 for(const [width,height]of [[1440,920],[852,393],[568,320]]){
 const p=await open(width,height,seed),mobile=width<1000,read=()=>p.evaluate(()=>DreamGame.inspect().state);
 const shot=label=>p.screenshot({animations:'disabled',path:out+'/simple-bag-'+label+'-'+width+'.png'});
 assert.equal(await p.locator('.bag-tabs button').count(),4);assert((await p.locator('.bag-tabs').textContent()).includes('간식'));assert(await p.locator('#bagGrade').isHidden());assert(await p.locator('#gearWorkshop').isHidden());await shot('list');
 await p.click('[data-item="tideBaton"]');assert.equal(await p.evaluate(()=>DreamGame.inspect().modalKind),'bag');assert(await p.locator('#gearCopy').isHidden());assert((await p.locator('.item-detail h3').textContent()).includes('+2'));
 await p.click('#equipItem');let s=await read();const uid=s.rpg.equippedUids.weapon;assert.equal(s.rpg.gear.find(g=>g.uid===uid).level,2);assert.equal(s.rpg.equipment.weapon,'tideBaton');assert((await p.locator('.bag-message').textContent()).includes('쓰고 있어요'));await shot('equipped');
 await p.click('#bagUpgrade');const detailWidth=await p.locator('.item-detail').boundingBox(),bodyWidth=await p.locator('.kit-detail-body').boundingBox();assert(bodyWidth.width>detailWidth.width*.8,'detail uses panel width');assert.equal(await p.evaluate(()=>DreamGame.inspect().modalKind),'bag');assert((await p.locator('.bag-upgrade').textContent()).includes('14개'));const before=await read();await p.click('#bagUpgradeCancel');assert.deepEqual((await read()).rpg,before.rpg,'cancel spends nothing');await p.click('#bagUpgrade');await shot('upgrade');
 if(mobile){const r=await p.locator('#bagUpgradeConfirm').boundingBox();assert(r.y>=0&&r.y+r.height<=height&&r.height>=43.5,'upgrade button fixed and touch sized');const gain=await p.locator('.bag-upgrade dl').boundingBox(),cost=await p.locator('.bag-upgrade p').first().boundingBox();assert(gain.y>=0&&gain.y+gain.height<=r.y,'gain visible before confirmation');assert(cost.y>=0&&cost.y+cost.height<=r.y,'cost visible before confirmation');}
 // The old click handler cannot upgrade twice and charge twice.
 await p.evaluate(()=>window.oldUpgrade=document.getElementById('bagUpgradeConfirm').onclick);await p.click('#bagUpgradeConfirm');s=await read();assert.equal(s.rpg.fragments,before.rpg.fragments-14);assert.equal(s.rpg.gear.find(g=>g.uid===uid).level,3);assert.equal(s.rpg.gear.filter(g=>g.itemId==='tideBaton'&&g.uid!==uid)[0].level,0);await p.evaluate(()=>oldUpgrade());assert.equal((await read()).rpg.fragments,s.rpg.fragments);assert.equal(await p.evaluate(()=>DreamGame.inspect().modalKind),'bag');
 if(mobile)await p.click('#bagListBack');await p.click('[data-bag-tab="costume"]');await p.click('[data-item="softScarf"]');const initial=(await read()).world.look.neck;await p.click('#wearBagLook');assert.equal((await read()).world.look.neck,initial==='softScarf'?null:'softScarf');assert.equal(await p.evaluate(()=>DreamGame.inspect().modalKind),'bag');
 if(mobile)await p.click('#bagListBack');await p.click('[data-bag-tab="supply"]');await p.click('[data-item="cookie"]');await p.click('#useItem');s=await read();assert.equal(s.rpg.inventory.cookie||0,0);assert.equal(s.hp,5);assert((await p.locator('.item-detail h3').textContent()).includes('쿠키'));assert.equal(await p.locator('#useItem').textContent(),'다 먹었어요');assert(await p.locator('#useItem').isDisabled());await shot('snack');
 const overflow=await p.locator('#modalContent,.bag-center,.item-detail,.bag-upgrade,.bag-wearing').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&e.scrollWidth>e.clientWidth+3).map(e=>e.className));assert.deepEqual(overflow,[]);
 await p.click('#modalClose');await p.reload();await p.waitForFunction(()=>DreamGame.inspect().mode==='title');await p.click('#continueButton');const saved=await read();assert.equal(saved.rpg.equippedUids.weapon,uid);assert.equal(saved.rpg.gear.find(g=>g.uid===uid).level,3);assert.equal(saved.rpg.inventory.cookie||0,0);await p.close();
 }
 for(const [name,change,text]of [['locked',s=>s.flags.metLumen=false,'루멘'],['poor',s=>s.rpg.fragments=0,'부족'],['maximum',s=>s.rpg.gear.find(g=>g.itemId==='baton').level=5,'최대 +5']]){const s=structuredClone(seed);change(s);const p=await open(852,393,s);await p.click('[data-bag-equipped="weapon"]');await p.click('#bagUpgrade');assert(await p.locator('#bagUpgradeConfirm').isDisabled());assert((await p.locator('.bag-upgrade').textContent()).includes(text),name);await p.close();}
 const full=structuredClone(seed);full.hp=6;const p=await open(852,393,full);await p.click('[data-bag-tab="supply"]');await p.click('[data-item="cookie"]');assert(await p.locator('#useItem').isDisabled());assert.equal(await p.evaluate(()=>DreamGame.inspect().state.rpg.inventory.cookie),1);await p.close();
 assert.deepEqual(errors,[]);console.log('PASS 3 sizes: four simple categories; equip/cosmetic/use/upgrade stay in bag; best copy default; preview/cancel; exact cost/UID; stale duplicate blocked; last snack stable; full health/unlock/funds/+5 guards; reload persistence');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
