const {chromium}=require('playwright'),assert=require('assert/strict'),path=require('path'),fs=require('fs');
const url=process.env.GAME_URL||'http://127.0.0.1:8769/',key='dreamy-nights-chapter-one-v1',out=path.resolve(__dirname,'../test-results');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN}),errors=[];try{
 const setup=await b.newPage();await setup.addInitScript(()=>localStorage.setItem('dreamy-nights-opening-v1','seen'));await setup.goto(url);await setup.waitForFunction(()=>window.DreamGame?.inspect().mode==='title');await setup.click('#startButton');await setup.click('#confirmHero');await setup.click('#dialogueSkip');
 const seed=await setup.evaluate(()=>{const s=DreamGame.inspect().state;s.flags.introSeen=true;s.flags.firstMemory=true;s.flags.metLumen=true;s.map=2;s.x=400;s.y=651;s.hp=3;for(const [id,it]of Object.entries(DREAM_CONTENT.items))if(it.type==='equipment')DREAM_GEAR.add(s.rpg,id,2);else if(it.type==='material')s.rpg.inventory[id]=50;else if(it.type==='supply')s.rpg.inventory[id]=8;s.pets.owned=Object.entries(DREAM_PETS.species).map(([species,v],i)=>({species,name:v.name,xp:i*15+5,affinity:20+i*10,assist:i}));s.pets.claims=['welcome','explorer','homecoming'];s.pets.active='leafFox';return s;});await setup.close();
 for(const [width,height]of [[1440,920],[852,393],[568,320]]){
 const mobile=width<1000,p=await b.newPage({viewport:{width,height},isMobile:mobile,hasTouch:mobile});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({key,seed})=>{localStorage.setItem(key,JSON.stringify(seed));localStorage.setItem('dreamy-nights-opening-v1','seen');localStorage.setItem('dreamy-nights-settings-v1',JSON.stringify({sound:false,voice:false}));},{key,seed});await p.goto(url);await p.waitForFunction(()=>window.DreamGame?.inspect().mode==='title');await p.click('#continueButton');await p.click('#inventoryButton');
 const fit=async()=>{const r=await p.locator('#modal .modal-card').boundingBox();assert(r.x>=-.5&&r.y>=-.5&&r.x+r.width<=width+.5&&r.y+r.height<=height+.5,'frame fits');assert.equal(await p.locator('.modal-card > .kit-nav').count(),1);assert.equal(await p.locator('.kit-nav button').count(),5);const overflow=await p.locator('#modalContent,.kit-nav,.keeper-layout,.pet-layout,.pet-growth,.pet-collection').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&e.scrollWidth>e.clientWidth+3).map(e=>[e.className,e.clientWidth,e.scrollWidth]));assert.deepEqual(overflow,[]);if(mobile){for(const e of await p.locator('.kit-nav button,#modalClose').all()){const r=await e.boundingBox();assert(r.width>=43.5&&r.height>=43.5,'44px navigation');}}};
 const shot=async label=>{await p.locator('#modalContent').evaluate(e=>e.scrollTop=0);await p.screenshot({animations:'disabled',path:out+'/panels-'+label+'-'+width+'.png'});};await fit();await shot('bag');
 const navBefore=await p.locator('.kit-nav').boundingBox();
 if(mobile){const cdp=await p.context().newCDPSession(p),r=await p.locator('#modalContent').boundingBox();const touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});const x=r.x+r.width-14,y=r.y+r.height-20;await touch('touchStart',[{x,y,id:1}]);for(let n=1;n<=9;n++)await touch('touchMove',[{x,y:y-n*12,id:1}]);await touch('touchEnd',[]);await p.waitForTimeout(120);assert((await p.locator('#modalContent').evaluate(e=>e.scrollTop))>10,'real touch scroll inside frame');}
 await p.locator('#modalContent').evaluate(e=>e.scrollTop=e.scrollHeight);assert.deepEqual(await p.locator('.kit-nav').boundingBox(),navBefore,'navigation stays fixed');
 await p.click('[data-kit-page="characterDetail"]');await fit();await shot('character');await p.click('[data-keeper-pose="run"]');assert.equal(await p.textContent('#keeperPoseLabel'),'달리기');await p.click('[data-kit-page="wardrobe"]');await fit();await shot('wardrobe');
 await p.click('[data-kit-page="pets"]');await fit();await shot('pets');assert.equal(await p.locator('[data-kit-page="pets"]').getAttribute('aria-current'),'page');await p.click('[data-pet-pick="tideOtter"]');const before=await p.evaluate(()=>DreamGame.inspect().state);await p.click('#petFeed');const after=await p.evaluate(()=>DreamGame.inspect().state);assert.equal(after.rpg.inventory.cookie,before.rpg.inventory.cookie-1);assert.equal(after.pets.owned[0].xp,before.pets.owned[0].xp+4);if(mobile){const r=await p.locator('#petFeed').boundingBox();assert(r.y>=0&&r.y+r.height<=height,'pet care action stays on screen');}await p.click('#petFollow');assert.equal(await p.evaluate(()=>DreamGame.inspect().state.pets.active),'tideOtter');
 await p.click('.pet-rename summary');await p.fill('#petName','반짝이');await p.click('.pet-name button');assert.equal(await p.evaluate(()=>DreamGame.inspect().state.pets.owned[0].name),'반짝이');await p.click('.kit-help summary');assert(await p.locator('.pet-next').isVisible());await p.click('[data-kit-page="growth"]');await fit();await shot('growth');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.modal-card').evaluate(e=>getComputedStyle(e).animationName),'none');await p.click('#modalClose');assert.equal(await p.evaluate(()=>DreamGame.inspect().mode),'play');await p.close();
 }
 // A first-time keeper sees the same frame for an egg gift and hatching.
 const p=await b.newPage({viewport:{width:852,height:393},isMobile:true,hasTouch:true});p.on('pageerror',e=>errors.push(e.message));const baby=structuredClone(seed);baby.pets={version:1,owned:[],egg:null,claims:[],active:null,visited:[],encounters:[]};await p.addInitScript(({key,seed})=>{localStorage.setItem(key,JSON.stringify(seed));localStorage.setItem('dreamy-nights-opening-v1','seen');},{key,seed:baby});await p.goto(url);await p.waitForFunction(()=>window.DreamGame?.inspect().mode==='title');await p.click('#continueButton');await p.keyboard.press('p');await p.click('#petChoose');assert.equal(await p.locator('#modal').getAttribute('data-kit'),'true');await p.screenshot({animations:'disabled',path:out+'/panels-eggs-852.png'});await p.click('[data-pet-egg="leafFox"]');await p.click('#petAccept');for(let i=0;i<4;i++)await p.click('#petWarm');await p.click('#petHatch');assert.equal(await p.evaluate(()=>DreamGame.inspect().modalKind),'petHatch');assert.equal(await p.locator('.kit-nav button').count(),5);await p.click('#petHello');assert.equal(await p.evaluate(()=>DreamGame.inspect().state.pets.owned[0].species),'leafFox');
 assert.deepEqual(errors,[]);console.log('PASS 3 sizes: fixed five-tab frame, no horizontal overflow, equipment/looks/pets/skills, pet selection/feed/name, egg/hatch, reduced motion');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
