const {chromium}=require('playwright'),path=require('path'),assert=require('assert/strict');
const url=process.env.GAME_URL||'file://'+path.resolve(__dirname,'../index.html');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN});try{for(const hero of ['ari','popo']){
const p=await b.newPage({viewport:{width:1440,height:920}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{localStorage.setItem('dreamy-nights-opening-v1','seen');localStorage.setItem('dreamy-nights-settings-v1',JSON.stringify({sound:false,soundChosen:true,voice:false}));let q=[],t=0;requestAnimationFrame=f=>(q.push(f),q.length);window.__step=n=>{for(let i=0;i<n;i++){t+=1000/60;const a=q;q=[];a.forEach(f=>f(t));}};});await p.goto(url);await p.waitForFunction(()=>window.DreamGame?.inspect().mode==='title',null,{timeout:60000});await p.evaluate(()=>{const draw=DreamRenderer.prototype.draw;DreamRenderer.prototype.draw=function(r){window.__r=r;return draw.call(this,r);};});await p.click('#startButton');await p.click(`[data-hero="${hero}"]`);await p.click('#confirmHero');await p.click('#dialogueSkip');const step=n=>p.evaluate(n=>__step(n),n),state=()=>p.evaluate(()=>DreamGame.inspect());await step(3);await p.evaluate(()=>{__r.enemies.forEach(e=>e.dead=true);__r.state.flags.firstMemory=true;__r.state.flags.metLumen=true;__r.state.flags.walkHint=true;__r.player.invincible=100;});
let x=(await state()).player.x;await p.keyboard.down('ArrowRight');await step(20);await p.keyboard.up('ArrowRight');assert((await state()).player.x>x+10);await step(30);x=(await state()).player.x;await p.keyboard.down('ArrowLeft');await step(15);await p.keyboard.up('ArrowLeft');assert((await state()).player.x<x-10);await step(30);
x=(await state()).player.x;await p.keyboard.down('a');await step(3);assert((await state()).player.chargeHeld);assert.equal((await state()).player.x,x);await p.keyboard.up('a');assert((await state()).player.pendingStrike);await step(50);
await p.keyboard.down('a');await step(70);assert((await state()).player.chargeReady);await p.keyboard.up('a');assert.equal((await state()).player.pendingStrike.impact,'charged');await step(60);
await p.keyboard.down('Space');await step(6);await p.keyboard.up('Space');await p.keyboard.press('Space');await step(3);assert((await state()).player.airJumpUsed);await p.keyboard.press('a');assert((await state()).player.plunge);await step(70);
await p.keyboard.press('s');assert((await state()).state.growth.skillCD>0);assert(!(await state()).controls.keyboard.includes('KeyS'));await step(40);await p.keyboard.press('d');assert((await state()).player.dodgeT>0);await step(100);
await p.evaluate(()=>{__r.state.hp=1;__r.state.rpg.inventory.cookie=3;__r.state.rpg.resonance=100;});await p.keyboard.press('q');assert((await state()).state.hp>1);assert.equal((await state()).mode,'play');await p.keyboard.press('f');assert.equal((await state()).state.rpg.resonance,0);
await p.keyboard.press('w');assert.equal((await state()).modalKind,'bag');await p.keyboard.press('w');assert.equal((await state()).mode,'play');await p.keyboard.press('c');assert(['wardrobe','characterDetail'].includes((await state()).modalKind));await p.keyboard.press('c');assert.equal((await state()).mode,'play');
await p.keyboard.press('Control+a');assert(!(await state()).player.chargeHeld);await p.keyboard.down('ArrowRight');await p.keyboard.down('a');await step(2);assert((await state()).controls.keyboard.includes('ArrowRight'));assert((await state()).controls.keyboard.includes('KeyA'));await p.keyboard.up('a');await p.keyboard.up('ArrowRight');await step(40);
assert.equal(await p.locator('#attackControl kbd').innerText(),'A');assert.equal(await p.locator('#skillControl kbd').innerText(),'S');assert.equal(await p.locator('#dodgeControl kbd').innerText(),'D');assert.equal(await p.locator('#snackButton kbd').innerText(),'Q');assert.deepEqual(errors,[]);console.log('PASS',hero,'arrows / A tap-hold-plunge / double jump / S-D-F-Q / W-C menus / combined input / modifier shortcut / labels');await p.close();}
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
