const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),c={};c.window=c;
for(const n of ['story','rpg-content','world-content','remaster-content','illustrated-content','exploration-content','art-v49','loot-content','tide-content','region-art','region-content','region-layout','chapter-one','progression-system'])vm.runInNewContext(fs.readFileSync(path.join(root,n+'.js'),'utf8'),c);
const P=c.DREAM_PROGRESS,C=c.DREAM_CONTENT,plain=s=>JSON.parse(JSON.stringify(s)),fresh=()=>P.initialize({active:'ari',xp:0,map:0,visited:[0],memories:[],killed:[],flags:{},hp:6,rpg:{resonance:42}});let n=0;function test(name,f){f();console.log('PASS',name);n++;}
test('All curve boundaries and first-country point milestones',()=>{const s=fresh();for(let lv=1;lv<=20;lv++){s.growth.xp=P.threshold(lv);assert.equal(P.level(s),lv);assert.equal(P.info(s).current,0);assert.equal(P.points(s),Math.min(5,Math.floor(lv/2)));}});
test('Legacy XP, level and partial progress are preserved; no retrospective duplicate rewards',()=>{for(const xp of[0,74,75,500,900,10000]){const s=fresh();s.xp=xp;s.flags.metLumen=true;s.visited=[0,1,2];const raw=plain(s);delete raw.growth;P.initialize(s,raw);assert.equal(s.xp,xp);assert.equal(P.level(s),1+Math.floor(xp/75));assert.equal(P.sync(s),0);}});
test('Quest, discovery and memory XP are awarded once and survive reload',()=>{const s=fresh();s.flags.metLumen=true;s.visited=[0,1,2];s.memories=[C.memories[0].id];const xp=P.sync(s);assert.equal(xp,76);assert.equal(P.sync(s),0);const raw=plain(s);P.initialize(s,raw);assert.equal(P.sync(s),0);assert.equal(s.xp,76);});
test('A complete first-world route reaches level 10 without repeat spawns',()=>{const s=fresh();for(const m of C.maps){for(const e of m.enemies.filter(e=>!e.wild)){s.killed.push(e.id);P.gain(s,C.creatures[e.type].exp);}}s.visited=C.maps.map((_,i)=>i);s.memories=C.memories.map(m=>m.id);for(const q of C.quests)if(q.flag)s.flags[q.flag]=true;for(const q of Object.values(C.sideQuests))s.flags[q.flag]=true;P.sync(s);assert.equal(P.level(s),10);assert.equal(P.points(s),5);console.log('  completion XP:',s.growth.xp);});
test('No missing prerequisites, overspending or double learning; 3+2 build works',()=>{const s=fresh();assert(!P.learn(s,'attack',1));s.growth.xp=P.threshold(10);assert(!P.learn(s,'attack',3));for(const [b,k]of[['attack',1],['attack',2],['attack',3],['guard',1],['guard',2]])assert(P.learn(s,b,k));assert(!P.learn(s,'attack',1));assert(!P.learn(s,'control',1));assert.equal(s.growth.passives.length,2);assert.equal(P.skill(s).damage,10);});
test('Free reset and switching require harbor/camp, preserve energy and cooldowns',()=>{const s=fresh();s.growth.xp=P.threshold(10);P.learn(s,'guard',1);s.growth.skillCD=7;s.growth.guardCD=20;assert(!P.reset(s,{grounded:true,x:900,y:651}));s.map=2;const before=[s.xp,s.hp,s.rpg.resonance];assert(P.reset(s,{}));assert.equal(s.growth.skillCD,7);assert.equal(s.growth.guardCD,20);assert.deepEqual([s.xp,s.hp,s.rpg.resonance],before);assert.equal(P.info(s).available,5);assert.equal(s.growth.active,'base');});
test('Malformed state cannot add arbitrary nodes, a third passive or non-finite cooldowns',()=>{const s=fresh();s.growth.xp=P.threshold(10);const raw=plain(s);raw.growth.nodes=['attack3','guard2','constructor1','attack1','attack1'];raw.growth.passives=['attack','guard','control'];raw.growth.active='constructor';raw.growth.skillCD=Infinity;P.initialize(s,raw);assert.deepEqual(plain(s.growth.nodes),['attack1']);assert.equal(s.growth.active,'base');assert.equal(s.growth.passives.length,0);assert.equal(s.growth.skillCD,0);});
test('All six selectable skills and free base skill cast, cooldown and restore safely',()=>{for(const hero of['ari','popo'])for(const branch of['attack','guard','control']){const s=fresh(),p={facing:1};s.active=hero;s.map=2;s.growth.xp=P.threshold(10);for(const k of[1,2,3])P.learn(s,branch,k);const spec=P.cast(s,p);assert.equal(spec.id,branch);assert(!P.cast(s,p));P.tick(s,p,.5);const cd=s.growth.skillCD,raw=plain(s);P.initialize(s,raw);assert.equal(s.growth.skillCD,cd);P.equip(s,'base','active',p);assert(!P.cast(s,p));P.tick(s,p,12);assert(P.cast(s,p));}});
console.log(n+' progression checks passed');
