const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const url=process.env.GAME_URL||'http://127.0.0.1:8769/';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN});try{for(const [width,height] of [[1440,920],[844,390],[568,320]]){
 const p=await browser.newPage({viewport:{width,height},isMobile:width<1000,hasTouch:width<1000}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{localStorage.setItem('dreamy-nights-opening-v1','seen');localStorage.setItem('dreamy-nights-settings-v1',JSON.stringify({sound:false,voice:false}));});await p.goto(url);await p.waitForFunction(()=>window.DreamGame?.inspect().mode==='title');await p.click('#startButton');await p.click('#confirmHero');await p.click('#dialogueSkip');await p.click('#inventoryButton');await p.click('[data-kit-page="wardrobe"]');
 assert.equal(await p.locator('#lookOwnership').count(),0);assert.deepEqual(await p.locator('[data-look]').evaluateAll(es=>es.map(e=>e.dataset.look)),['softScarf']);assert(!(await p.locator('.kit-collection').textContent()).includes('/'));assert.equal(await p.locator('[data-craft-look]').count(),0);
 await p.click('[data-look-filter="head"]');assert.equal(await p.locator('[data-look]').count(),0);assert.equal(await p.locator('.costume-detail h3').count(),0);assert((await p.locator('.empty-bag').textContent()).includes('모험에서 얻으면'));await p.click('[data-kit-page="characterDetail"]');await p.click('[data-keeper-slot="head"][data-keeper-look]');assert.equal(await p.locator('[data-look]').count(),0);
 await p.click('[data-look-filter="all"]');await p.screenshot({path:path.resolve(__dirname,`../test-results/owned-wardrobe-${width}.png`),animations:'disabled'});await p.click('[data-look="softScarf"]');await p.click('#wearLook');assert.equal(await p.evaluate(()=>DreamGame.inspect().state.world.look.neck),null);assert.equal(await p.locator('[data-look="softScarf"]').count(),1);await p.click('#wearLook');assert.equal(await p.evaluate(()=>DreamGame.inspect().state.world.look.neck),'softScarf');assert.deepEqual(errors,[]);await p.close();
 }console.log('PASS 3 sizes: only owned items, no missing selector/count, empty slot and character shortcut safe, unequipping retains owned item');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
