"""Soft rising movement whistles, deliberately separate from rubber impact percussion."""
from pathlib import Path
import math, wave, struct, random, json
ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'assets/audio-v440'
DEST.mkdir(exist_ok=True)
SR = 32000
manifest = {}
for hero, start, end in [('ari', 880, 1820), ('popo', 650, 1360)]:
    for double in [False, True]:
        name = f'action-{"doubleJump" if double else "jump"}-{hero}'
        duration = .225 if double else .185
        length = round(SR * duration)
        rng = random.Random(440 + int(double))
        phase, previous_noise = 0., 0.
        samples = []
        for i in range(length):
            u = i / (length - 1)
            t = i / SR
            # Continuous upward pitch and a slow rounded onset: no impact transient,
            # falling rubber pitch, membrane rebound, or strike sample reuse.
            frequency = (start + (end - start) * u ** .8) * (1.18 if double else 1)
            if double:
                frequency *= 1 + .012 * math.sin(2 * math.pi * 21 * t)
            phase += 2 * math.pi * frequency / SR
            envelope = math.sin(math.pi * u) ** 1.45
            noise = rng.uniform(-1, 1)
            breath = .025 * (noise - previous_noise)
            previous_noise = noise
            tone = math.sin(phase) + .045 * math.sin(2 * phase)
            samples.append((tone + breath) * envelope)
        peak = max(map(abs, samples))
        samples = [s * .52 / peak for s in samples]
        with wave.open(str(DEST / (name + '.wav')), 'wb') as out:
            out.setparams((1, 2, SR, 0, 'NONE', 'not compressed'))
            out.writeframes(b''.join(struct.pack('<h', round(s * 32767)) for s in samples))
        manifest[name] = {'file': f'assets/audio-v440/{name}.wav', 'seconds': duration,
                          'design': 'soft continuous rising breath whistle; no impact percussion',
                          'peak': .52, 'hero': hero, 'airJump': double}
(DEST / 'sources.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
(DEST / 'CREDITS.txt').write_text('Our Dreamy Nights v4.40.0 — jump movement sound design.\nCopyright 2026 Aznail (김광석), to the extent legally protectable; see ../../LICENSE.txt.\nFour original offline synthesized rising breath whistles, no third-party samples or attack/impact percussion.\nGenerated by tools/build-jump-audio.py using the Python standard library. PCM 16-bit mono, 32 kHz.\n')
# Reapply movement overrides after regenerating the older combat sound collection.
asset_file = ROOT / 'combat-audio-assets.js'
text = asset_file.read_text()
assets = json.loads(text.split('Object.assign(DREAM_AUDIO_ASSETS.effects,', 1)[1].rsplit(');', 1)[0])
assets.update({key: {'file': clip['file']} for key, clip in manifest.items()})
asset_file.write_text("'use strict';\nObject.assign(DREAM_AUDIO_ASSETS.effects," + json.dumps(assets, indent=2) + ');\n')
print('Generated four movement-only clips:', ', '.join(manifest))
